#workflow name
name: Pulse - Daily Summary Bot

on:
    schedule:
        - cron: '30 2 * * *'
    workflow_dispatch:

jobs:
    run-pulse:
        runs-on: ubuntu-latest

        steps:
          -  name: Checkout code
             uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5

          - name: Install dependencies
            run: pip install -r requirements.txt

          - name: Run Pulse bot
            env:
               SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
               APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
               RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
            run: python bot.py

          - name: Upload summary as artifact
            uses: actions/upload-artifact@v4
            with: 
                name: daily-summary
                path: daily_summary.txt